version: 1.0.0
name: MY PROD RELEASES
apps:
  - uuid: 26e0ba10-c111-11f0-92c6-eb6c0554fb80
    release: 1.0.0
  - uuid: 4aac3d00-dcb1-11f0-8f57-8f5705c56169
    release: latest
  - uuid: 563555e4-c104-11f0-8458-6facc3a0dfda
    release: 1.0.0
  - uuid: 7c995470-c38d-11f0-a3d0-bba1fab677a2
    release: latest
  - uuid: d062c50e-dcac-11f0-894a-0370954a9f4c
    release: latest
  - uuid: ef76ad8e-dbe9-11f0-8c18-cfdb89002ed8
    release: latest
workflows:
  - uuid: 58996cc0-fe9c-4ecd-ab46-91c44951669a
    release: latest
  - uuid: 6843ef35-10c6-43e1-b801-60c24373e478
    release: latest
