version: 1.0.0
name: MY STAGING RELEASE
apps:
  - uuid: 26e0ba10-c111-11f0-92c6-eb6c0554fb80
    release: 2.0.1
  - uuid: 563555e4-c104-11f0-8458-6facc3a0dfda
    release: 2.0.0
  - uuid: 7c995470-c38d-11f0-a3d0-bba1fab677a2
    release: latest
workflows:
  - uuid: 6843ef35-10c6-43e1-b801-60c24373e478
    release: latest
